config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  devise_for :users
  resources :users, only: [:index,:show]

  resources :images, only: [:index, :show, :update]
  resources :challenges
end

app/views/layouts/application.haml
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %meta{:content => "", :name => "description"}
    %meta{:content => "", :name => "author"}
    %title Phazam
    / Phazam CSS
    = stylesheet_link_tag 'application'
    / Phazam JS
    = javascript_include_tag 'application'
    / Phazam CSRF Meta
    = csrf_meta_tags
    / Bootstrap Core CSS
    %link{:href => "/startbootstrap/css/bootstrap.min.css", :rel => "stylesheet", :type => "text/css"}
    / Custom Fonts
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic", :rel => "stylesheet", :type => "text/css"}
    %link{:href => "/startbootstrap/font-awesome/css/font-awesome.min.css", :rel => "stylesheet", :type => "text/css"}
      / Plugin CSS
    %link{:href => "/startbootstrap/css/animate.min.css", :rel => "stylesheet", :type => "text/css"}
      / Custom CSS
    %link{:href => "/startbootstrap/css/creative.css", :rel => "stylesheet", :type => "text/css"}
      / Social CSS
    %link{:href => "https://github.com/lipis/bootstrap-social/blob/gh-pages/bootstrap-social.css", :rel => "stylesheet", :type => "text/css"}
      / HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries
      / WARNING: Respond.js doesn't work if you view the page via file://
      /[if lt IE 9]
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  %body
    %nav#mainNav.navbar.navbar-default.navbar-fixed-top
      .container-fluid
        / Brand and toggle get grouped for better mobile display
        .navbar-header
          %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          - if current_page?('/')
            %a.navbar-brand.page-scroll{:href => "#page-top"} Phazam
          - else
            %a.navbar-brand.page-scroll{:href => "/"} Phazam
        / Collect the nav links, forms, and other content for toggling
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav.navbar-left
            %li= link_to "View Photos",images_path
            - if current_user
              %li= link_to "Start A New Challenge", new_challenge_path
              /%li= link_to "Load Photos", controller: :image, action: :load
          %ul.nav.navbar-nav.navbar-right
            - if current_page?('/')
              %li
                %a.page-scroll{:href => "#about"} About
              %li
                %a.page-scroll{:href => "#features"} Features
              %li
                %a.page-scroll{:href => "#portfolio"} Portfolio
              %li
                %a.page-scroll{:href => "#contact"} Contact
            - if current_user
              %li.dropdown
                %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
                  = current_user.name || current_user.email
                  %span.caret
                %ul.dropdown-menu
                  %li= link_to (current_user.name || current_user.email), current_user
                  %li= link_to "Edit", edit_user_registration_path
                  %li= link_to "Logout", destroy_user_session_path, :method => :delete
            - else
              %li= link_to "Sign In", new_user_session_path
              %li= link_to "Sign Up", new_user_registration_path
  .page-begin
    - if flash[:notice]
      .alert.alert-success
        %button{type: "button",class: "close",dismiss: "alert"} &times;
        = flash[:notice]
    - elsif flash[:error]
      .alert.alert-danger
        %button{type: "button",class: "close",dismiss: "alert"} &times;
        = flash[:error]
    - elsif flash[:alert]
      .alert.alert-warning
        %button{type: "button",class: "close",dismiss: "alert"} &times;
        = flash[:alert]
    = yield
  %section#contact
    .container
      .row
        .col-lg-8.col-lg-offset-2.text-center
          %h2.section-heading Let's Get In Touch!
          %hr.primary
        .col-lg-3.text-center
          %a.btn.btn-lg.btn-social-icon.btn-linkedin.wow.bounceIn
            %span.glyphicon.glyphicon-envelope
          %p
            %a{:href => "mailto:fong.fan.90@gmail.com"} Email
        .col-lg-3.text-center
          %a.btn.btn-lg.btn-social-icon.btn-twitter.wow.bounceIn{"data-wow-delay" => ".3s"}
            %span.fa.fa-twitter
          %p
            %a{:href => "https://twitter.com/fongvoltfan"} Twitter
        .col-lg-3.text-center
          %a.btn.btn-lg.btn-social-icon.btn-large.btn-github.wow.bounceIn{"data-wow-delay" => ".6s"}
            %span.fa.fa-github
          %p
            %a{:href => "https://github.com/voltaaage"} GitHub
        .col-lg-3.text-center
          %a.btn.btn-lg.btn-social-icon.btn-linkedin.wow.bounceIn{"data-wow-delay" => ".9s"}
            %span.fa.fa-linkedin
          %p
            %a{:href => "https://www.linkedin.com"} LinkedIn
  / jQuery
  %script{:src => "/startbootstrap/js/jquery.js"}
  / Bootstrap Core JavaScript
  %script{:src => "/startbootstrap/js/bootstrap.min.js"}
  / Plugin JavaScript
  %script{:src => "/startbootstrap/js/jquery.easing.min.js"}
  %script{:src => "/startbootstrap/js/jquery.fittext.js"}
  %script{:src => "/startbootstrap/js/wow.min.js"}
  / Custom Theme JavaScript
  %script{:src => "/startbootstrap/js/creative.js"}